version: '2'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "dev_trello_scheduled"
      POSTGRES_USER: "postgres"
    
    ports:
      - "5432:5432"

  redis:
    image: redis

    ports:
      - "6379:6379"