"""empty message

Revision ID: 9f0192af896e
Revises: e38d08621411
Create Date: 2016-08-06 00:34:50.552589

"""

# revision identifiers, used by Alembic.
revision = '9f0192af896e'
down_revision = 'e38d08621411'

from alembic import op
import sqlalchemy as sa
import models


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recurring_card', sa.Column('frequency_kind', sa.Integer(), nullable=True))
    op.add_column('recurring_card', sa.Column('frequency_val', sa.Integer(), nullable=True))
    op.add_column('recurring_card', sa.Column('list', sa.String(length=255), nullable=True))
    op.drop_column('recurring_card', 'column')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recurring_card', sa.Column('column', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('recurring_card', 'list')
    op.drop_column('recurring_card', 'frequency_val')
    op.drop_column('recurring_card', 'frequency_kind')
    ### end Alembic commands ###
