"""empty message

Revision ID: c282d3b368e3
Revises: None
Create Date: 2016-08-05 21:08:46.987479

"""

# revision identifiers, used by Alembic.
revision = 'c282d3b368e3'
down_revision = None

from alembic import op
import sqlalchemy as sa
import models
import sqlalchemy_utcdatetime


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('trello_id', sa.String(length=255), nullable=True),
    sa.Column('trello_token', sa.String(length=255), nullable=True),
    sa.Column('trello_token_exp', sqlalchemy_utcdatetime.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trello_id')
    )
    op.create_table('recurring_card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('labels', sa.String(length=255), nullable=True),
    sa.Column('board', sa.String(length=255), nullable=True),
    sa.Column('column', sa.String(length=255), nullable=True),
    sa.Column('start', sqlalchemy_utcdatetime.UTCDateTime(), nullable=True),
    sa.Column('last_run', sqlalchemy_utcdatetime.UTCDateTime(), nullable=True),
    sa.Column('frequency', sa.Interval(), nullable=True),
    sa.Column('due_date_minutes', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recurring_card')
    op.drop_table('user')
    ### end Alembic commands ###
