"""empty message

Revision ID: e38d08621411
Revises: c282d3b368e3
Create Date: 2016-08-05 23:35:07.768343

"""

# revision identifiers, used by Alembic.
revision = 'e38d08621411'
down_revision = 'c282d3b368e3'

from alembic import op
import sqlalchemy as sa
import models
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recurring_card', sa.Column('due_date_int', sa.Interval(), nullable=True))
    op.drop_column('recurring_card', 'due_date_minutes')
    op.drop_column('user', 'trello_token_exp')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('trello_token_exp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('recurring_card', sa.Column('due_date_minutes', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('recurring_card', 'due_date_int')
    ### end Alembic commands ###
